ln -s custom_components/peblar/__init__.py .
ln -s custom_components/peblar/binary_sensor.py .
ln -s custom_components/peblar/config_flow.py .
ln -s custom_components/peblar/const.py .
ln -s custom_components/peblar/controller.py .
ln -s custom_components/peblar/diagnostics.py .
ln -s custom_components/peblar/entity.py .
ln -s custom_components/peblar/manifest.json .
ln -s custom_components/peblar/sensor.py .
ln -s custom_components/peblar/services.py .
ln -s custom_components/peblar/services.yaml .
ln -s custom_components/peblar/switch.py .
ln -s custom_components/peblar/system_health.py .
ln -s custom_components/peblar/translations .
ln -s custom_components/peblar/device_action.py .
ln -s custom_components/peblar/device_condition.py .
ln -s custom_components/peblar/device_trigger.py .
